### ISSUE TITLE
Does not remove the Windows 11 shortcut.

### ISSUE THREAD

**Issue by ghost** [asheroto/UninstallTeams#1]
Using `Win + C` will still open this pop-up:

![image](https://github.com/asheroto/UninstallTeams/assets/129807902/82cd7eac-8db2-4675-b742-a0cf03e69294)

**Comment by asheroto** [comment]
Hello,

I checked on this. When you press Win+C and click "Continue", Windows installs Microsoft Teams. If you run UninstallTeams, it does actually remove the software associated with that...

![image](https://github.com/asheroto/UninstallTeams/assets/49938263/92bdf6a0-e6da-4eea-8f5c-dcfa54c8f573)

![image](https://github.com/asheroto/UninstallTeams/assets/49938263/116576bb-ff98-42e4-a0ef-a662b0eeaba8)


If I press Win+C and click "Continue" again, it Teams will be uninstalled.

UninstallTeams won't remove the ability to press Win+C, it just uninstalls Teams itself. The Win+C hotkey is a feature of Windows, not of Teams.

You can disable the Chat widget or widgets entirely. More information on [this answer](https://superuser.com/a/1765054/1142621). If you are using a Home edition of Windows you won't have group policy editor, but you can create the associated registry keys by Googling the text in that answer.

Technically disabling the Chat widget goes beyond the scope of this project, however, since it seems like it would be a common request, I spent a few hours and updated the script with the ability to enable/disable the chat widget. 😊 Lots of changes! Thanks!

https://github.com/asheroto/UninstallTeams/releases
