### ISSUE TITLE
Match Error

### ISSUE THREAD

**Issue by johns33** [asheroto/UninstallTeams#5]
This script matches "Teams" so if there is other software on your computer that starts for Teams it will also be uninstalled.

**Comment by asheroto** [comment]
Ah, thanks for mentioning that. I could see where some software may be removed that shouldn't. I'll work on an update.

**Comment by asheroto** [comment]
@johns33 what software are you using that matches with Teams?

The issue I'm running into is that Microsoft tends to use different names for Teams. Some matches are `Microsoft Teams`, others are `Teams Machine-Wide Installer`, and various processes such as `Teams.exe` and `ms-teams.exe`, among others. Matching `*Teams*` although not perfect, tends to work for most folks.

Since there's so many variations, I may need to just keep the wildcard match for now, but can build in an exclusion if you need it.
